version: '3'

services:
    rhino:
        image: 'clivern/rhino:release-1.6.2'
        ports:
            - "8080:8080"
        command: '/app/rhino serve -c /app/configs/config.prod.json'
        volumes:
            - './configs/:/app/configs'
        restart: unless-stopped
