version: '3'

services:
    rhino:
        image: 'clivern/rhino:release-1.6.1'
        ports:
            - "8080:8080"
        command: '/app/rhino serve -c /app/configs/config.prod.json'
        volumes:
            - './configs/:/app/configs'
        restart: unless-stopped

    loki:
        image: grafana/loki:2.6.1
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - loki

    promtail:
        image: grafana/promtail:2.6.1
        volumes:
            - './configs/:/var/log'
        command: -config.file=/etc/promtail/config.yml
        networks:
            - loki

    prometheus:
        image: 'prom/prometheus:v2.37.0'
        volumes:
            - './prometheus/:/etc/prometheus'
        command: '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
        restart: unless-stopped

    grafana:
        image: 'grafana/grafana:9.0.3'
        environment:
            - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
            - GF_USERS_ALLOW_SIGN_UP=false
        ports:
            - '3000:3000'
        depends_on:
            - prometheus
        restart: unless-stopped
        networks:
          - loki


networks:
  loki:
