name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.11', '1.12', '1.13', '1.14', '1.15']
    name: Go ${{ matrix.go }} run
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: |
          make install_revive

      - name: Run make ci
        run: |
          make ci
          git status
          git diff > diff.log
          cat diff.log
          git clean -fd
          git reset --hard
          make verify
